spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/envie}
    username: ${SPRING_DATASOURCE_USERNAME:test_user}
    password: ${SPRING_DATASOURCE_PASSWORD:pass1}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

management:
  endpoints:
    web:
      base-path: /api/v1/actuator

envie:
  upload-dir: ${UPLOAD_DIR:./uploads}
  templates-dir: ${TEMPLATES_DIR:../templates}
  anthropic-api-key: ${ANTHROPIC_API_KEY:}
